version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "maven"
    directory: "/geoservice-isochrone-v2/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "maven"
    directory: "/dbf2csv/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/geoservice-map-vue3/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"
