UPDATE public.parc_jardin SET nom_parc='Square Félix Thomas' WHERE nom_parc='Square F�lix Thomas';
UPDATE public.parc_jardin SET nom_parc='Square de la Tchécoslovaquie' WHERE nom_parc='Square de la Tch�coslovaquie';
UPDATE public.parc_jardin SET nom_parc='Belvédère Sainte-Anne' WHERE nom_parc='Belv�d�re Sainte-Anne';
UPDATE public.parc_jardin SET nom_parc='Parc de Procé' WHERE nom_parc='Parc de Proc�';
UPDATE public.parc_jardin SET nom_parc='Jardin du Musée Dobrée' WHERE nom_parc='Jardin du Mus�e Dobr�e';
UPDATE public.parc_jardin SET nom_parc='Parc de la Méta' WHERE nom_parc='Parc de la M�ta';
UPDATE public.parc_jardin SET nom_parc='Square Faustin Hélie' WHERE nom_parc='Square Faustin H�lie';
UPDATE public.parc_jardin SET nom_parc='Square Corrèze' WHERE nom_parc='Square Corr�ze';
UPDATE public.parc_jardin SET nom_parc='Square Saint François' WHERE nom_parc='Square Saint Fran�ois';
UPDATE public.parc_jardin SET nom_parc='Jardin de l''hôtel de Ville' WHERE nom_parc='Jardin de l''h�tel de Ville';
UPDATE public.parc_jardin SET nom_parc='Square René Cassin' WHERE nom_parc='Square Ren� Cassin';
UPDATE public.parc_jardin SET nom_parc='Parc du Bout des Pavés' WHERE nom_parc='Parc du Bout des Pav�s';
UPDATE public.parc_jardin SET nom_parc='Parc de la Noë Mitrie' WHERE nom_parc='Parc de la No� Mitrie';
UPDATE public.parc_jardin SET nom_parc='Square de la Halvêque' WHERE nom_parc='Square de la Halv�que';
UPDATE public.parc_jardin SET nom_parc='Square des Grands Pâtis' WHERE nom_parc='Square des Grands P�tis';
UPDATE public.parc_jardin SET nom_parc='Square René-Guy Cadou' WHERE nom_parc='Square Ren�-Guy Cadou';
UPDATE public.parc_jardin SET nom_parc='Square du Vieux Parc de Sèvres' WHERE nom_parc='Square du Vieux Parc de S�vres';
UPDATE public.parc_jardin SET nom_parc='Jardin du Réservoir' WHERE nom_parc='Jardin du R�servoir';
UPDATE public.parc_jardin SET nom_parc='Square de la Pilotière' WHERE nom_parc='Square de la Piloti�re';
UPDATE public.parc_jardin SET nom_parc='Square Jules Bréchoir' WHERE nom_parc='Square Jules Br�choir';
UPDATE public.parc_jardin SET nom_parc='Square Général de la Bollardière' WHERE nom_parc='Square G�n�ral de la Bollardi�re';
UPDATE public.parc_jardin SET nom_parc='Square des Ingénieurs' WHERE nom_parc='Square des Ing�nieurs';
UPDATE public.parc_jardin SET nom_parc='Jardin des douves du Ch�teau' WHERE nom_parc='Jardin des douves du Ch�teau';
UPDATE public.parc_jardin SET nom_parc='Square Félix Faure' WHERE nom_parc='Square F�lix Faure';
UPDATE public.parc_jardin SET nom_parc='Square Gabriel Chéreau' WHERE nom_parc='Square Gabriel Ch�reau';
UPDATE public.parc_jardin SET nom_parc='Parc Bottière-Chenaie' WHERE nom_parc='Parc Botti�re-Chenaie';
UPDATE public.parc_jardin SET nom_parc='Parc de la Gaudinière' WHERE nom_parc='Parc de la Gaudini�re';
UPDATE public.parc_jardin SET nom_parc='Parc de la Boucardière' WHERE nom_parc='Parc de la Boucardi�re';
UPDATE public.parc_jardin SET nom_parc='Square Maquis de Saffré' WHERE nom_parc='Square Maquis de Saffr�';
UPDATE public.parc_jardin SET nom_parc='Parc du Chêne des Anglais' WHERE nom_parc='Parc du Ch�ne des Anglais';
UPDATE public.parc_jardin SET nom_parc='Square Pascal Lebée' WHERE nom_parc='Square Pascal Leb�e';
UPDATE public.parc_jardin SET nom_parc='Jardin des Maraîches' WHERE nom_parc='Jardin des Mara�ches';
UPDATE public.parc_jardin SET nom_parc='Place de la Guirouée' WHERE nom_parc='Place de la Guirou�e';
UPDATE public.parc_jardin SET nom_parc='Square Méliès' WHERE nom_parc='Square M�li�s';
UPDATE public.parc_jardin SET nom_parc='Parc des Dervallières' WHERE nom_parc='Parc des Dervalli�res';
UPDATE public.parc_jardin SET nom_parc='Jardin de l''île Mabon' WHERE nom_parc='Jardin de l''�le Mabon';
UPDATE public.parc_jardin SET nom_parc='Jardin de la Persagotière' WHERE nom_parc='Jardin de la Persagoti�re';
UPDATE public.parc_jardin SET nom_parc='Parc de la Boissière' WHERE nom_parc='Parc de la Boissi�re';
UPDATE public.parc_jardin SET nom_parc='Jardin d''Enfants de Procé' WHERE nom_parc='Jardin d''Enfants de Proc�';
UPDATE public.parc_jardin SET nom_parc='Square Bénoni Goulin' WHERE nom_parc='Square B�noni Goulin';
