server:
  servlet:
    contextPath: /isochrone
    
management:
  endpoints.web.exposure:
    include: "*"
    exclude: env, beans
  endpoint:
    health.show-details: always
    shutdown.enabled: true
  metrics:
    tags.application: ${spring.application.name}
    export.simple.enabled: false

               
web:
  cors:
    allowed-origins: http://localhost:8980/,http://localhost:5173/,http://localhost:8981/

# Config for PROD
spring:
  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    format-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/isochrone?useTimeZone=true&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: autmel
    password: YCxvCF5rQTNFXNtT8mYw
  thymeleaf:
    cache: true
    enable-spring-el-compiler: true
    
application:
  deployed_url: https://asso.autmel.ovh/
  security:
    export-credential-key: 32a2b286c5cc3f3fbb33601e44696cab45d018b934ef8b03a345677d054f2dd3
    export-ip-address: 192.168.1.0
    timehack: 3500
    jwt-sign-key: FAKE_KEY
    salt-len: 150
    hash-len: 128
    nb-iters: 31
    nb-threads: 2
#    1 << 15  =32768
#    1 << 17  =131072
    memSizeInKb: 32768
  mailjet:
    apiToken: 5d1076459d4f685e738397469ab2e9d5
    apiSecret: 4c780648294efe12bbb76ebcb347f2d1
    senderEmail: lmh2d2021@gmail.com
    senderName: AUT'MEL
    attachementPath: /var/isochrone/mail/
  feature-flipping:
    sendEmail: true
    parkAnalysisEnabled: true
    salaryAnalysisEnabled: false
    pollutionAnalysisEnabled: false
    isochrone-impl: ign-api-v2
    carre200m-impl: v2
    
  admin:
    export-path: /work/PERSO/github/gh_pages/geoservice-data/data
    photo-path: /work/PERSO/ASSO/isochrone/photo
    photo-path-origin: /work/PERSO/ASSO/isochrone/photo_origin
    export-data-path: /work/PERSO/github/gh_pages/geoservice-data
   

ISOCHRONE_SITE_GESTION: https://asso.autmel.ovh/isochrone/
ISOCHRONE_SITE_GESTION_SPARE: https://autmel-map.hd.free.fr/isochrone/
ISOCHRONE_SITE_PUBLIQUE: https://autmel.github.io/geoservice/
