# https://medium.com/@ksandeeptech07/integrating-prometheus-with-spring-boot-for-metrics-alerts-and-monitoring-5b2c31995ddb
# https://levelup.gitconnected.com/java-23-springboot-3-3-4-metrics-micrometer-aop-part-6-808dcb97dcb7


# zipkin + sleuth
spring:
    sleuth:
        sampler.probability: 1.0
    zipkin:
        baseUrl: http://zipkin:9411/
        sender.type: web
    
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
      connect-timeout: 1s
      read-timeout: 10s
