# https://medium.com/@ksandeeptech07/integrating-prometheus-with-spring-boot-for-metrics-alerts-and-monitoring-5b2c31995ddb

# https://levelup.gitconnected.com/java-23-springboot-3-3-4-metrics-micrometer-aop-part-6-808dcb97dcb7


# zipkin + sleuth
spring:
    sleuth:
        sampler.probability: 1.0
#        reactor.instrumentation-type: decorate-on-last
    zipkin:
        baseUrl: http://zipkin:9411/
        sender.type: web
    
    
# JMX
spring.datasource.hikari.registerMbeans: true

management:
# zipkin + brave
  tracing:
    enabled: true
    sampling:
      probability: 1.0
      enabled: true
  propagation:
    type: w3c
  baggage:
    correlation:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
      connect-timeout: 1s
      read-timeout: 10s
#      encoding: [JSON]
# prometheus
  endpoints.web.exposure:
    include: prometheus,health,info,metric
    exclude: env,configprops,shutdown,heapdump,threaddump, beans
  endpoint:
    health.show-details: always
    shutdown.enabled: false
    prometheus.enabled: true
  metrics:
    distribution.percentiles-histogram.http:
        server.requests: true
        client.requests: true
    tags.application: ${spring.application.name}
    export.simple.enabled: true
    export.prometheus.enabled: true
  health.probes.enabled: true
    

# embeded tomcat    
server.tomcat:
  accesslog:
    enabled: false
    suffix: .log
    prefix: access_log
    file-date-format: .yyyy-MM-dd
    pattern: common
    directory: /var/log/jvm
#  basedir: /var/log/jvm
  
logging:
  level:
    org.apache.tomcat: ERROR
    org.apache.catalina: ERROR
    org.springframework.web: DEBUG
    com.github.cunvoas.geoserviceisochrone: DEBUG
  pattern.level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] [%t] %C{2} - %m%n"
  
#  level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
