version: "3.3" 
services:

  letsencrypt-forum:
    container_name: 'certbot-service-forum'
    env_file: ../secret.env
    image: certbot/certbot:latest
#    command: sh -c "certbot certonly --webroot -w /tmp/acme_challenge -d ${AUTMEL_FORUM} --text --agree-tos --email=${AUTMEL_EMAIL} --rsa-key-size 2028 --verbose --keep-until-expiring --preferred-challenges=dns,http"
    command: sh -c "certbot certonly --force-renew --webroot -w /tmp/acme_challenge -d ${AUTMEL_FORUM} --text --agree-tos --email=${AUTMEL_EMAIL} --rsa-key-size 2028 --verbose --keep-until-expiring --preferred-challenges=dns,http"
    entrypoint: ""
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme_challenge:/tmp/acme_challenge"
    environment:
      - TERM=xterm
