version: "3"

services:
  app:
    image: matomo
    restart: unless-stopped
    volumes:
#     - ./config:/var/www/html/config:z
#     - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./secret.env
    ports:
      - 444:8080

volumes:
  matomo: