-- https://fr.wikipedia.org/wiki/Lille#Communes_limitrophes
-- lille = 59350

/* too long
 
INSERT INTO public.cadastre_proche( id_insee, insee_proche)
select distinct 
	cs.id_insee, ca.id_insee
	FROM public.cadastre ca, public.cadastre cs 
	where st_intersects(ca.geo_shape, 
	       ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round')
	   );
*/
	   
-- by dept
	   
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '01%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '02%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '03%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '04%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '05%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '06%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '07%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '08%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '09%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '10%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '11%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '12%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '13%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '14%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '15%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '16%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '17%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '18%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '19%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '20%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '21%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '22%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '23%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '24%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '25%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '26%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '27%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '28%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '29%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '30%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '31%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '32%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '33%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '34%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '35%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '36%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '37%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '38%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '39%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '40%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '41%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '42%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '43%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '44%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '45%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '46%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '47%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '48%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '49%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '50%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '51%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '52%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '53%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '54%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '55%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '56%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '57%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '58%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '59%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '60%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '61%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '62%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '63%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '64%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '65%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '66%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '67%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '68%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '69%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '70%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '71%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '72%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '73%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '74%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '75%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '76%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '77%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '78%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '79%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '80%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '81%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '82%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '83%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '84%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '85%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '86%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '87%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '88%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '89%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '90%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '91%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '92%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '93%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '94%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
INSERT INTO public.cadastre_proche( id_insee, insee_proche) select distinct cs.id_insee, ca.id_insee FROM public.cadastre ca, public.cadastre cs where cs.id_insee like '95%' and st_intersects(ca.geo_shape, ST_Buffer( cs.geo_shape , 0.005, 'endcap=round join=round') ); 
